from enum import Enum


class Verdict(Enum):
    PROMISING = "PROMISING — VALIDATE IN DISCOVERY"
    INVESTIGATE = "INVESTIGATE"
    BUY_CONFIGURE = "BUY / CONFIGURE"
    ONE_OFF = "ONE-OFF CUSTOM PROJECT"
    POOR_TARGET = "POOR TARGET CUSTOMER"
    NO_DEAL = "NO DEAL"
